default_language_version:
    python: python3

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      name: black
      entry: bash -c "black ."
      always_run: true

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort
      files: "\\.(py)$"
      entry: bash -c "isort ."
      always_run: true

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      name: flake8
      entry: bash -c "flake8 ."
      always_run: true
