version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh ./entrypoint.sh
    restart: unless-stopped
    env_file:
      - envs/.env

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run python src/manage.py migrate"
    profiles:
      - migrate
    env_file:
      - envs/.env

  collectstatic:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "poetry run python src/manage.py collectstatic --noinput --clear"
    profiles:
      - collectstatic
    env_file:
      - envs/.env

  redis:
    image: "redis:latest"
    restart: unless-stopped
    depends_on:
      - web
    expose:
      - 6379

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "cd src && poetry run celery --app config worker -l INFO"
    env_file:
      - envs/.env
    depends_on:
      - web
      - redis
    volumes:
      - .:/app

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "cd src && poetry run celery --app config beat -l INFO"
    env_file:
      - envs/.env
    depends_on:
      - web
      - redis
      - celery-worker
    volumes:
      - .:/app
