version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "cd src && poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - 8000
