version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh ./entrypoint.sh
    restart: unless-stopped
    env_file:
      - envs/.env

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "cd src && poetry run python src/manage.py migrate"
    profiles:
      - migrate
    env_file:
      - envs/.env

  collectstatic:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "cd src && poetry run python src/manage.py collectstatic --noinput --clear"
    profiles:
      - collectstatic
    env_file:
      - envs/.env
