# Generated by Django 4.1.1 on 2022-10-30 14:28

import common.validators
import dirtyfields.dirtyfields
from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('file', models.FileField(upload_to='messages/media/%Y/%m/%d/', validators=[functools.partial(common.validators.validate_file_size, *(), **{'max_size': 1048576000})])),
            ],
            options={
                'verbose_name': 'Meдия сообщения',
                'verbose_name_plural': 'Медия сообщений',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.profile', verbose_name='Первый участник')),
                ('second_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.profile', verbose_name='Второй участник')),
            ],
            options={
                'verbose_name': 'Личное',
                'verbose_name_plural': 'Личные',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='Содержимое')),
                ('chat_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', related_query_name='reply', to='chats.message')),
                ('chat_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'chats'), ('model', 'chat')), models.Q(('app_label', 'chats'), ('model', 'privatechat')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='profiles.profile')),
                ('medias', models.ManyToManyField(blank=True, related_name='messages', related_query_name='messages', to='chats.media')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Elected',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elected_messages', to='profiles.profile')),
                ('messages', models.ManyToManyField(blank=True, to='chats.message')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время изменения записи')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('members', models.ManyToManyField(blank=True, related_name='chats', to='profiles.profile', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='privatechat',
            constraint=models.CheckConstraint(check=models.Q(('first_member', models.F('second_member')), _negated=True), name='check_private_member', violation_error_message='Users cannot send message to themselves.'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together={('first_member', 'second_member')},
        ),
    ]
