# Generated by Django 4.1.1 on 2022-12-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electedmessage',
            options={'verbose_name': 'ElectedMessage', 'verbose_name_plural': 'ElectedMessages'},
        ),
    ]
